/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as ConfiancaRouteImport } from './routes/confianca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as GSlugIndexRouteImport } from './routes/g.$slug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as GSlugExplorarRouteImport } from './routes/g.$slug.explorar'
import { Route as ApiPublicGuideChatRouteImport } from './routes/api/public/guide-chat'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminBibliotecaRouteImport } from './routes/_authenticated/admin.biblioteca'
import { Route as AuthenticatedAdminAssinaturaRouteImport } from './routes/_authenticated/admin.assinatura'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminPropertiesIdRouteImport } from './routes/_authenticated/admin.properties.$id'
import { Route as AuthenticatedAdminPropertiesIdConversasRouteImport } from './routes/_authenticated/admin.properties.$id_.conversas'
import { Route as AuthenticatedAdminPropertiesIdAcessosRouteImport } from './routes/_authenticated/admin.properties.$id_.acessos'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiancaRoute = ConfiancaRouteImport.update({
  id: '/confianca',
  path: '/confianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GSlugIndexRoute = GSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GSlugRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const GSlugExplorarRoute = GSlugExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => GSlugRoute,
} as any)
const ApiPublicGuideChatRoute = ApiPublicGuideChatRouteImport.update({
  id: '/api/public/guide-chat',
  path: '/api/public/guide-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBibliotecaRoute =
  AuthenticatedAdminBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssinaturaRoute =
  AuthenticatedAdminAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPropertiesIdRoute =
  AuthenticatedAdminPropertiesIdRouteImport.update({
    id: '/properties/$id',
    path: '/properties/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIdConversasRoute =
  AuthenticatedAdminPropertiesIdConversasRouteImport.update({
    id: '/properties/$id_/conversas',
    path: '/properties/$id/conversas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIdAcessosRoute =
  AuthenticatedAdminPropertiesIdAcessosRouteImport.update({
    id: '/properties/$id_/acessos',
    path: '/properties/$id/acessos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/g/$slug': typeof GSlugRouteWithChildren
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/assinatura': typeof AuthenticatedAdminAssinaturaRoute
  '/admin/biblioteca': typeof AuthenticatedAdminBibliotecaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/api/public/guide-chat': typeof ApiPublicGuideChatRoute
  '/g/$slug/explorar': typeof GSlugExplorarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/g/$slug/': typeof GSlugIndexRoute
  '/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/properties/$id/acessos': typeof AuthenticatedAdminPropertiesIdAcessosRoute
  '/admin/properties/$id/conversas': typeof AuthenticatedAdminPropertiesIdConversasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/assinatura': typeof AuthenticatedAdminAssinaturaRoute
  '/admin/biblioteca': typeof AuthenticatedAdminBibliotecaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/api/public/guide-chat': typeof ApiPublicGuideChatRoute
  '/g/$slug/explorar': typeof GSlugExplorarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/g/$slug': typeof GSlugIndexRoute
  '/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/properties/$id/acessos': typeof AuthenticatedAdminPropertiesIdAcessosRoute
  '/admin/properties/$id/conversas': typeof AuthenticatedAdminPropertiesIdConversasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/g/$slug': typeof GSlugRouteWithChildren
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/assinatura': typeof AuthenticatedAdminAssinaturaRoute
  '/_authenticated/admin/biblioteca': typeof AuthenticatedAdminBibliotecaRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/api/public/guide-chat': typeof ApiPublicGuideChatRoute
  '/g/$slug/explorar': typeof GSlugExplorarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/g/$slug/': typeof GSlugIndexRoute
  '/_authenticated/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/admin/properties/$id_/acessos': typeof AuthenticatedAdminPropertiesIdAcessosRoute
  '/_authenticated/admin/properties/$id_/conversas': typeof AuthenticatedAdminPropertiesIdConversasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confianca'
    | '/precos'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/admin'
    | '/g/$slug'
    | '/admin/admins'
    | '/admin/assinatura'
    | '/admin/biblioteca'
    | '/admin/clientes'
    | '/api/public/guide-chat'
    | '/g/$slug/explorar'
    | '/admin/'
    | '/g/$slug/'
    | '/admin/properties/$id'
    | '/api/public/payments/webhook'
    | '/admin/properties/$id/acessos'
    | '/admin/properties/$id/conversas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confianca'
    | '/precos'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/admin/admins'
    | '/admin/assinatura'
    | '/admin/biblioteca'
    | '/admin/clientes'
    | '/api/public/guide-chat'
    | '/g/$slug/explorar'
    | '/admin'
    | '/g/$slug'
    | '/admin/properties/$id'
    | '/api/public/payments/webhook'
    | '/admin/properties/$id/acessos'
    | '/admin/properties/$id/conversas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confianca'
    | '/precos'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/_authenticated/admin'
    | '/g/$slug'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/assinatura'
    | '/_authenticated/admin/biblioteca'
    | '/_authenticated/admin/clientes'
    | '/api/public/guide-chat'
    | '/g/$slug/explorar'
    | '/_authenticated/admin/'
    | '/g/$slug/'
    | '/_authenticated/admin/properties/$id'
    | '/api/public/payments/webhook'
    | '/_authenticated/admin/properties/$id_/acessos'
    | '/_authenticated/admin/properties/$id_/conversas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiancaRoute: typeof ConfiancaRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  TermosRoute: typeof TermosRoute
  GSlugRoute: typeof GSlugRouteWithChildren
  ApiPublicGuideChatRoute: typeof ApiPublicGuideChatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confianca': {
      id: '/confianca'
      path: '/confianca'
      fullPath: '/confianca'
      preLoaderRoute: typeof ConfiancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/g/$slug/': {
      id: '/g/$slug/'
      path: '/'
      fullPath: '/g/$slug/'
      preLoaderRoute: typeof GSlugIndexRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/g/$slug/explorar': {
      id: '/g/$slug/explorar'
      path: '/explorar'
      fullPath: '/g/$slug/explorar'
      preLoaderRoute: typeof GSlugExplorarRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/api/public/guide-chat': {
      id: '/api/public/guide-chat'
      path: '/api/public/guide-chat'
      fullPath: '/api/public/guide-chat'
      preLoaderRoute: typeof ApiPublicGuideChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/biblioteca': {
      id: '/_authenticated/admin/biblioteca'
      path: '/biblioteca'
      fullPath: '/admin/biblioteca'
      preLoaderRoute: typeof AuthenticatedAdminBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinatura': {
      id: '/_authenticated/admin/assinatura'
      path: '/assinatura'
      fullPath: '/admin/assinatura'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/properties/$id': {
      id: '/_authenticated/admin/properties/$id'
      path: '/properties/$id'
      fullPath: '/admin/properties/$id'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/$id_/conversas': {
      id: '/_authenticated/admin/properties/$id_/conversas'
      path: '/properties/$id/conversas'
      fullPath: '/admin/properties/$id/conversas'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdConversasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/$id_/acessos': {
      id: '/_authenticated/admin/properties/$id_/acessos'
      path: '/properties/$id/acessos'
      fullPath: '/admin/properties/$id/acessos'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdAcessosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAssinaturaRoute: typeof AuthenticatedAdminAssinaturaRoute
  AuthenticatedAdminBibliotecaRoute: typeof AuthenticatedAdminBibliotecaRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPropertiesIdRoute: typeof AuthenticatedAdminPropertiesIdRoute
  AuthenticatedAdminPropertiesIdAcessosRoute: typeof AuthenticatedAdminPropertiesIdAcessosRoute
  AuthenticatedAdminPropertiesIdConversasRoute: typeof AuthenticatedAdminPropertiesIdConversasRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAssinaturaRoute: AuthenticatedAdminAssinaturaRoute,
  AuthenticatedAdminBibliotecaRoute: AuthenticatedAdminBibliotecaRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPropertiesIdRoute: AuthenticatedAdminPropertiesIdRoute,
  AuthenticatedAdminPropertiesIdAcessosRoute:
    AuthenticatedAdminPropertiesIdAcessosRoute,
  AuthenticatedAdminPropertiesIdConversasRoute:
    AuthenticatedAdminPropertiesIdConversasRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GSlugRouteChildren {
  GSlugExplorarRoute: typeof GSlugExplorarRoute
  GSlugIndexRoute: typeof GSlugIndexRoute
}

const GSlugRouteChildren: GSlugRouteChildren = {
  GSlugExplorarRoute: GSlugExplorarRoute,
  GSlugIndexRoute: GSlugIndexRoute,
}

const GSlugRouteWithChildren = GSlugRoute._addFileChildren(GSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiancaRoute: ConfiancaRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  TermosRoute: TermosRoute,
  GSlugRoute: GSlugRouteWithChildren,
  ApiPublicGuideChatRoute: ApiPublicGuideChatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
