/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ConfiancaRouteImport } from './routes/confianca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as GSlugIndexRouteImport } from './routes/g.$slug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth.google-calendar.return'
import { Route as GSlugExplorarRouteImport } from './routes/g.$slug.explorar'
import { Route as ApiPublicPlacePhotoRouteImport } from './routes/api/public/place-photo'
import { Route as ApiPublicLandingChatRouteImport } from './routes/api/public/landing-chat'
import { Route as ApiPublicGuideChatUploadRouteImport } from './routes/api/public/guide-chat-upload'
import { Route as ApiPublicGuideChatRouteImport } from './routes/api/public/guide-chat'
import { Route as ApiPublicGuestPushRouteImport } from './routes/api/public/guest-push'
import { Route as ApiPublicGuestDocUploadRouteImport } from './routes/api/public/guest-doc-upload'
import { Route as ApiPublicClicksignWebhookRouteImport } from './routes/api/public/clicksign-webhook'
import { Route as AuthenticatedAdminTaxonomiaRouteImport } from './routes/_authenticated/admin.taxonomia'
import { Route as AuthenticatedAdminStakeholdersRouteImport } from './routes/_authenticated/admin.stakeholders'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin.permissoes'
import { Route as AuthenticatedAdminInteligenciaRouteImport } from './routes/_authenticated/admin.inteligencia'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as AuthenticatedAdminIaRouteImport } from './routes/_authenticated/admin.ia'
import { Route as AuthenticatedAdminHospedesRouteImport } from './routes/_authenticated/admin.hospedes'
import { Route as AuthenticatedAdminGuiasRouteImport } from './routes/_authenticated/admin.guias'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminEngajamentoRouteImport } from './routes/_authenticated/admin.engajamento'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminAtendimentoRouteImport } from './routes/_authenticated/admin.atendimento'
import { Route as AuthenticatedAdminAssinaturaRouteImport } from './routes/_authenticated/admin.assinatura'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as AuthenticatedAdminAdministrativoRouteImport } from './routes/_authenticated/admin.administrativo'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminRecomendacoesSigmaIndexRouteImport } from './routes/_authenticated/admin.recomendacoes-sigma.index'
import { Route as AuthenticatedAdminCidadesIndexRouteImport } from './routes/_authenticated/admin.cidades.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWhatsappSinchWebhookRouteImport } from './routes/api/public/whatsapp/sinch-webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronSyncAirbnbIcalRouteImport } from './routes/api/public/cron.sync-airbnb-ical'
import { Route as ApiPublicCronSaasAlertsRouteImport } from './routes/api/public/cron.saas-alerts'
import { Route as ApiPublicCronRefreshRecommendationsRouteImport } from './routes/api/public/cron.refresh-recommendations'
import { Route as ApiPublicCronRefreshCityReferencesRouteImport } from './routes/api/public/cron.refresh-city-references'
import { Route as ApiPublicCronRefreshCityNewsRouteImport } from './routes/api/public/cron.refresh-city-news'
import { Route as ApiPublicCronProactiveConciergeRouteImport } from './routes/api/public/cron.proactive-concierge'
import { Route as ApiPublicCronLearningLoopRouteImport } from './routes/api/public/cron.learning-loop'
import { Route as AuthenticatedAdminRecomendacoesSigmaCityKeyRouteImport } from './routes/_authenticated/admin.recomendacoes-sigma.$cityKey'
import { Route as AuthenticatedAdminPropertiesIdRouteImport } from './routes/_authenticated/admin.properties.$id'
import { Route as AuthenticatedAdminCidadesCityKeyRouteImport } from './routes/_authenticated/admin.cidades.$cityKey'
import { Route as AuthenticatedAdminPropertiesIdConversasRouteImport } from './routes/_authenticated/admin.properties.$id_.conversas'
import { Route as AuthenticatedAdminPropertiesIdAcessosRouteImport } from './routes/_authenticated/admin.properties.$id_.acessos'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiancaRoute = ConfiancaRouteImport.update({
  id: '/confianca',
  path: '/confianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const GSlugIndexRoute = GSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GSlugRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const GSlugExplorarRoute = GSlugExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => GSlugRoute,
} as any)
const ApiPublicPlacePhotoRoute = ApiPublicPlacePhotoRouteImport.update({
  id: '/api/public/place-photo',
  path: '/api/public/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandingChatRoute = ApiPublicLandingChatRouteImport.update({
  id: '/api/public/landing-chat',
  path: '/api/public/landing-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuideChatUploadRoute =
  ApiPublicGuideChatUploadRouteImport.update({
    id: '/api/public/guide-chat-upload',
    path: '/api/public/guide-chat-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGuideChatRoute = ApiPublicGuideChatRouteImport.update({
  id: '/api/public/guide-chat',
  path: '/api/public/guide-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestPushRoute = ApiPublicGuestPushRouteImport.update({
  id: '/api/public/guest-push',
  path: '/api/public/guest-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestDocUploadRoute = ApiPublicGuestDocUploadRouteImport.update({
  id: '/api/public/guest-doc-upload',
  path: '/api/public/guest-doc-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClicksignWebhookRoute =
  ApiPublicClicksignWebhookRouteImport.update({
    id: '/api/public/clicksign-webhook',
    path: '/api/public/clicksign-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminTaxonomiaRoute =
  AuthenticatedAdminTaxonomiaRouteImport.update({
    id: '/taxonomia',
    path: '/taxonomia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStakeholdersRoute =
  AuthenticatedAdminStakeholdersRouteImport.update({
    id: '/stakeholders',
    path: '/stakeholders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInteligenciaRoute =
  AuthenticatedAdminInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIaRoute = AuthenticatedAdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHospedesRoute =
  AuthenticatedAdminHospedesRouteImport.update({
    id: '/hospedes',
    path: '/hospedes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGuiasRoute = AuthenticatedAdminGuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEngajamentoRoute =
  AuthenticatedAdminEngajamentoRouteImport.update({
    id: '/engajamento',
    path: '/engajamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAtendimentoRoute =
  AuthenticatedAdminAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssinaturaRoute =
  AuthenticatedAdminAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdministrativoRoute =
  AuthenticatedAdminAdministrativoRouteImport.update({
    id: '/administrativo',
    path: '/administrativo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRecomendacoesSigmaIndexRoute =
  AuthenticatedAdminRecomendacoesSigmaIndexRouteImport.update({
    id: '/recomendacoes-sigma/',
    path: '/recomendacoes-sigma/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCidadesIndexRoute =
  AuthenticatedAdminCidadesIndexRouteImport.update({
    id: '/cidades/',
    path: '/cidades/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappSinchWebhookRoute =
  ApiPublicWhatsappSinchWebhookRouteImport.update({
    id: '/api/public/whatsapp/sinch-webhook',
    path: '/api/public/whatsapp/sinch-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncAirbnbIcalRoute =
  ApiPublicCronSyncAirbnbIcalRouteImport.update({
    id: '/api/public/cron/sync-airbnb-ical',
    path: '/api/public/cron/sync-airbnb-ical',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSaasAlertsRoute = ApiPublicCronSaasAlertsRouteImport.update({
  id: '/api/public/cron/saas-alerts',
  path: '/api/public/cron/saas-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshRecommendationsRoute =
  ApiPublicCronRefreshRecommendationsRouteImport.update({
    id: '/api/public/cron/refresh-recommendations',
    path: '/api/public/cron/refresh-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshCityReferencesRoute =
  ApiPublicCronRefreshCityReferencesRouteImport.update({
    id: '/api/public/cron/refresh-city-references',
    path: '/api/public/cron/refresh-city-references',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshCityNewsRoute =
  ApiPublicCronRefreshCityNewsRouteImport.update({
    id: '/api/public/cron/refresh-city-news',
    path: '/api/public/cron/refresh-city-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronProactiveConciergeRoute =
  ApiPublicCronProactiveConciergeRouteImport.update({
    id: '/api/public/cron/proactive-concierge',
    path: '/api/public/cron/proactive-concierge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronLearningLoopRoute =
  ApiPublicCronLearningLoopRouteImport.update({
    id: '/api/public/cron/learning-loop',
    path: '/api/public/cron/learning-loop',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRecomendacoesSigmaCityKeyRoute =
  AuthenticatedAdminRecomendacoesSigmaCityKeyRouteImport.update({
    id: '/recomendacoes-sigma/$cityKey',
    path: '/recomendacoes-sigma/$cityKey',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIdRoute =
  AuthenticatedAdminPropertiesIdRouteImport.update({
    id: '/properties/$id',
    path: '/properties/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCidadesCityKeyRoute =
  AuthenticatedAdminCidadesCityKeyRouteImport.update({
    id: '/cidades/$cityKey',
    path: '/cidades/$cityKey',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIdConversasRoute =
  AuthenticatedAdminPropertiesIdConversasRouteImport.update({
    id: '/properties/$id_/conversas',
    path: '/properties/$id/conversas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIdAcessosRoute =
  AuthenticatedAdminPropertiesIdAcessosRouteImport.update({
    id: '/properties/$id_/acessos',
    path: '/properties/$id/acessos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/mcp': typeof McpRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/g/$slug': typeof GSlugRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/administrativo': typeof AuthenticatedAdminAdministrativoRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/assinatura': typeof AuthenticatedAdminAssinaturaRoute
  '/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/engajamento': typeof AuthenticatedAdminEngajamentoRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/guias': typeof AuthenticatedAdminGuiasRoute
  '/admin/hospedes': typeof AuthenticatedAdminHospedesRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/inteligencia': typeof AuthenticatedAdminInteligenciaRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/stakeholders': typeof AuthenticatedAdminStakeholdersRoute
  '/admin/taxonomia': typeof AuthenticatedAdminTaxonomiaRoute
  '/api/public/clicksign-webhook': typeof ApiPublicClicksignWebhookRoute
  '/api/public/guest-doc-upload': typeof ApiPublicGuestDocUploadRoute
  '/api/public/guest-push': typeof ApiPublicGuestPushRoute
  '/api/public/guide-chat': typeof ApiPublicGuideChatRoute
  '/api/public/guide-chat-upload': typeof ApiPublicGuideChatUploadRoute
  '/api/public/landing-chat': typeof ApiPublicLandingChatRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
  '/g/$slug/explorar': typeof GSlugExplorarRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/g/$slug/': typeof GSlugIndexRoute
  '/admin/cidades/$cityKey': typeof AuthenticatedAdminCidadesCityKeyRoute
  '/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/admin/recomendacoes-sigma/$cityKey': typeof AuthenticatedAdminRecomendacoesSigmaCityKeyRoute
  '/api/public/cron/learning-loop': typeof ApiPublicCronLearningLoopRoute
  '/api/public/cron/proactive-concierge': typeof ApiPublicCronProactiveConciergeRoute
  '/api/public/cron/refresh-city-news': typeof ApiPublicCronRefreshCityNewsRoute
  '/api/public/cron/refresh-city-references': typeof ApiPublicCronRefreshCityReferencesRoute
  '/api/public/cron/refresh-recommendations': typeof ApiPublicCronRefreshRecommendationsRoute
  '/api/public/cron/saas-alerts': typeof ApiPublicCronSaasAlertsRoute
  '/api/public/cron/sync-airbnb-ical': typeof ApiPublicCronSyncAirbnbIcalRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/sinch-webhook': typeof ApiPublicWhatsappSinchWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/cidades/': typeof AuthenticatedAdminCidadesIndexRoute
  '/admin/recomendacoes-sigma/': typeof AuthenticatedAdminRecomendacoesSigmaIndexRoute
  '/admin/properties/$id/acessos': typeof AuthenticatedAdminPropertiesIdAcessosRoute
  '/admin/properties/$id/conversas': typeof AuthenticatedAdminPropertiesIdConversasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/mcp': typeof McpRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/administrativo': typeof AuthenticatedAdminAdministrativoRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/assinatura': typeof AuthenticatedAdminAssinaturaRoute
  '/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/engajamento': typeof AuthenticatedAdminEngajamentoRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/guias': typeof AuthenticatedAdminGuiasRoute
  '/admin/hospedes': typeof AuthenticatedAdminHospedesRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/inteligencia': typeof AuthenticatedAdminInteligenciaRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/stakeholders': typeof AuthenticatedAdminStakeholdersRoute
  '/admin/taxonomia': typeof AuthenticatedAdminTaxonomiaRoute
  '/api/public/clicksign-webhook': typeof ApiPublicClicksignWebhookRoute
  '/api/public/guest-doc-upload': typeof ApiPublicGuestDocUploadRoute
  '/api/public/guest-push': typeof ApiPublicGuestPushRoute
  '/api/public/guide-chat': typeof ApiPublicGuideChatRoute
  '/api/public/guide-chat-upload': typeof ApiPublicGuideChatUploadRoute
  '/api/public/landing-chat': typeof ApiPublicLandingChatRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
  '/g/$slug/explorar': typeof GSlugExplorarRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/g/$slug': typeof GSlugIndexRoute
  '/admin/cidades/$cityKey': typeof AuthenticatedAdminCidadesCityKeyRoute
  '/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/admin/recomendacoes-sigma/$cityKey': typeof AuthenticatedAdminRecomendacoesSigmaCityKeyRoute
  '/api/public/cron/learning-loop': typeof ApiPublicCronLearningLoopRoute
  '/api/public/cron/proactive-concierge': typeof ApiPublicCronProactiveConciergeRoute
  '/api/public/cron/refresh-city-news': typeof ApiPublicCronRefreshCityNewsRoute
  '/api/public/cron/refresh-city-references': typeof ApiPublicCronRefreshCityReferencesRoute
  '/api/public/cron/refresh-recommendations': typeof ApiPublicCronRefreshRecommendationsRoute
  '/api/public/cron/saas-alerts': typeof ApiPublicCronSaasAlertsRoute
  '/api/public/cron/sync-airbnb-ical': typeof ApiPublicCronSyncAirbnbIcalRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/sinch-webhook': typeof ApiPublicWhatsappSinchWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesIndexRoute
  '/admin/recomendacoes-sigma': typeof AuthenticatedAdminRecomendacoesSigmaIndexRoute
  '/admin/properties/$id/acessos': typeof AuthenticatedAdminPropertiesIdAcessosRoute
  '/admin/properties/$id/conversas': typeof AuthenticatedAdminPropertiesIdConversasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/mcp': typeof McpRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/g/$slug': typeof GSlugRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/administrativo': typeof AuthenticatedAdminAdministrativoRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/assinatura': typeof AuthenticatedAdminAssinaturaRoute
  '/_authenticated/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/engajamento': typeof AuthenticatedAdminEngajamentoRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/guias': typeof AuthenticatedAdminGuiasRoute
  '/_authenticated/admin/hospedes': typeof AuthenticatedAdminHospedesRoute
  '/_authenticated/admin/ia': typeof AuthenticatedAdminIaRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/inteligencia': typeof AuthenticatedAdminInteligenciaRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/stakeholders': typeof AuthenticatedAdminStakeholdersRoute
  '/_authenticated/admin/taxonomia': typeof AuthenticatedAdminTaxonomiaRoute
  '/api/public/clicksign-webhook': typeof ApiPublicClicksignWebhookRoute
  '/api/public/guest-doc-upload': typeof ApiPublicGuestDocUploadRoute
  '/api/public/guest-push': typeof ApiPublicGuestPushRoute
  '/api/public/guide-chat': typeof ApiPublicGuideChatRoute
  '/api/public/guide-chat-upload': typeof ApiPublicGuideChatUploadRoute
  '/api/public/landing-chat': typeof ApiPublicLandingChatRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
  '/g/$slug/explorar': typeof GSlugExplorarRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/g/$slug/': typeof GSlugIndexRoute
  '/_authenticated/admin/cidades/$cityKey': typeof AuthenticatedAdminCidadesCityKeyRoute
  '/_authenticated/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/_authenticated/admin/recomendacoes-sigma/$cityKey': typeof AuthenticatedAdminRecomendacoesSigmaCityKeyRoute
  '/api/public/cron/learning-loop': typeof ApiPublicCronLearningLoopRoute
  '/api/public/cron/proactive-concierge': typeof ApiPublicCronProactiveConciergeRoute
  '/api/public/cron/refresh-city-news': typeof ApiPublicCronRefreshCityNewsRoute
  '/api/public/cron/refresh-city-references': typeof ApiPublicCronRefreshCityReferencesRoute
  '/api/public/cron/refresh-recommendations': typeof ApiPublicCronRefreshRecommendationsRoute
  '/api/public/cron/saas-alerts': typeof ApiPublicCronSaasAlertsRoute
  '/api/public/cron/sync-airbnb-ical': typeof ApiPublicCronSyncAirbnbIcalRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/sinch-webhook': typeof ApiPublicWhatsappSinchWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/cidades/': typeof AuthenticatedAdminCidadesIndexRoute
  '/_authenticated/admin/recomendacoes-sigma/': typeof AuthenticatedAdminRecomendacoesSigmaIndexRoute
  '/_authenticated/admin/properties/$id_/acessos': typeof AuthenticatedAdminPropertiesIdAcessosRoute
  '/_authenticated/admin/properties/$id_/conversas': typeof AuthenticatedAdminPropertiesIdConversasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confianca'
    | '/mcp'
    | '/painel'
    | '/precos'
    | '/privacidade'
    | '/reembolso'
    | '/sitemap.xml'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/g/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/administrativo'
    | '/admin/admins'
    | '/admin/assinatura'
    | '/admin/atendimento'
    | '/admin/clientes'
    | '/admin/dashboard'
    | '/admin/engajamento'
    | '/admin/equipe'
    | '/admin/guias'
    | '/admin/hospedes'
    | '/admin/ia'
    | '/admin/integracoes'
    | '/admin/inteligencia'
    | '/admin/permissoes'
    | '/admin/stakeholders'
    | '/admin/taxonomia'
    | '/api/public/clicksign-webhook'
    | '/api/public/guest-doc-upload'
    | '/api/public/guest-push'
    | '/api/public/guide-chat'
    | '/api/public/guide-chat-upload'
    | '/api/public/landing-chat'
    | '/api/public/place-photo'
    | '/g/$slug/explorar'
    | '/oauth/google-calendar/return'
    | '/admin/'
    | '/g/$slug/'
    | '/admin/cidades/$cityKey'
    | '/admin/properties/$id'
    | '/admin/recomendacoes-sigma/$cityKey'
    | '/api/public/cron/learning-loop'
    | '/api/public/cron/proactive-concierge'
    | '/api/public/cron/refresh-city-news'
    | '/api/public/cron/refresh-city-references'
    | '/api/public/cron/refresh-recommendations'
    | '/api/public/cron/saas-alerts'
    | '/api/public/cron/sync-airbnb-ical'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/sinch-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/cidades/'
    | '/admin/recomendacoes-sigma/'
    | '/admin/properties/$id/acessos'
    | '/admin/properties/$id/conversas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confianca'
    | '/mcp'
    | '/painel'
    | '/precos'
    | '/privacidade'
    | '/reembolso'
    | '/sitemap.xml'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/administrativo'
    | '/admin/admins'
    | '/admin/assinatura'
    | '/admin/atendimento'
    | '/admin/clientes'
    | '/admin/dashboard'
    | '/admin/engajamento'
    | '/admin/equipe'
    | '/admin/guias'
    | '/admin/hospedes'
    | '/admin/ia'
    | '/admin/integracoes'
    | '/admin/inteligencia'
    | '/admin/permissoes'
    | '/admin/stakeholders'
    | '/admin/taxonomia'
    | '/api/public/clicksign-webhook'
    | '/api/public/guest-doc-upload'
    | '/api/public/guest-push'
    | '/api/public/guide-chat'
    | '/api/public/guide-chat-upload'
    | '/api/public/landing-chat'
    | '/api/public/place-photo'
    | '/g/$slug/explorar'
    | '/oauth/google-calendar/return'
    | '/admin'
    | '/g/$slug'
    | '/admin/cidades/$cityKey'
    | '/admin/properties/$id'
    | '/admin/recomendacoes-sigma/$cityKey'
    | '/api/public/cron/learning-loop'
    | '/api/public/cron/proactive-concierge'
    | '/api/public/cron/refresh-city-news'
    | '/api/public/cron/refresh-city-references'
    | '/api/public/cron/refresh-recommendations'
    | '/api/public/cron/saas-alerts'
    | '/api/public/cron/sync-airbnb-ical'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/sinch-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/cidades'
    | '/admin/recomendacoes-sigma'
    | '/admin/properties/$id/acessos'
    | '/admin/properties/$id/conversas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confianca'
    | '/mcp'
    | '/painel'
    | '/precos'
    | '/privacidade'
    | '/reembolso'
    | '/sitemap.xml'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/g/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/administrativo'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/assinatura'
    | '/_authenticated/admin/atendimento'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/engajamento'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/guias'
    | '/_authenticated/admin/hospedes'
    | '/_authenticated/admin/ia'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/inteligencia'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/stakeholders'
    | '/_authenticated/admin/taxonomia'
    | '/api/public/clicksign-webhook'
    | '/api/public/guest-doc-upload'
    | '/api/public/guest-push'
    | '/api/public/guide-chat'
    | '/api/public/guide-chat-upload'
    | '/api/public/landing-chat'
    | '/api/public/place-photo'
    | '/g/$slug/explorar'
    | '/oauth/google-calendar/return'
    | '/_authenticated/admin/'
    | '/g/$slug/'
    | '/_authenticated/admin/cidades/$cityKey'
    | '/_authenticated/admin/properties/$id'
    | '/_authenticated/admin/recomendacoes-sigma/$cityKey'
    | '/api/public/cron/learning-loop'
    | '/api/public/cron/proactive-concierge'
    | '/api/public/cron/refresh-city-news'
    | '/api/public/cron/refresh-city-references'
    | '/api/public/cron/refresh-recommendations'
    | '/api/public/cron/saas-alerts'
    | '/api/public/cron/sync-airbnb-ical'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/sinch-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/cidades/'
    | '/_authenticated/admin/recomendacoes-sigma/'
    | '/_authenticated/admin/properties/$id_/acessos'
    | '/_authenticated/admin/properties/$id_/conversas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiancaRoute: typeof ConfiancaRoute
  McpRoute: typeof McpRoute
  PainelRoute: typeof PainelRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  GSlugRoute: typeof GSlugRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicClicksignWebhookRoute: typeof ApiPublicClicksignWebhookRoute
  ApiPublicGuestDocUploadRoute: typeof ApiPublicGuestDocUploadRoute
  ApiPublicGuestPushRoute: typeof ApiPublicGuestPushRoute
  ApiPublicGuideChatRoute: typeof ApiPublicGuideChatRoute
  ApiPublicGuideChatUploadRoute: typeof ApiPublicGuideChatUploadRoute
  ApiPublicLandingChatRoute: typeof ApiPublicLandingChatRoute
  ApiPublicPlacePhotoRoute: typeof ApiPublicPlacePhotoRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicCronLearningLoopRoute: typeof ApiPublicCronLearningLoopRoute
  ApiPublicCronProactiveConciergeRoute: typeof ApiPublicCronProactiveConciergeRoute
  ApiPublicCronRefreshCityNewsRoute: typeof ApiPublicCronRefreshCityNewsRoute
  ApiPublicCronRefreshCityReferencesRoute: typeof ApiPublicCronRefreshCityReferencesRoute
  ApiPublicCronRefreshRecommendationsRoute: typeof ApiPublicCronRefreshRecommendationsRoute
  ApiPublicCronSaasAlertsRoute: typeof ApiPublicCronSaasAlertsRoute
  ApiPublicCronSyncAirbnbIcalRoute: typeof ApiPublicCronSyncAirbnbIcalRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWhatsappSinchWebhookRoute: typeof ApiPublicWhatsappSinchWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confianca': {
      id: '/confianca'
      path: '/confianca'
      fullPath: '/confianca'
      preLoaderRoute: typeof ConfiancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/': {
      id: '/g/$slug/'
      path: '/'
      fullPath: '/g/$slug/'
      preLoaderRoute: typeof GSlugIndexRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/explorar': {
      id: '/g/$slug/explorar'
      path: '/explorar'
      fullPath: '/g/$slug/explorar'
      preLoaderRoute: typeof GSlugExplorarRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/api/public/place-photo': {
      id: '/api/public/place-photo'
      path: '/api/public/place-photo'
      fullPath: '/api/public/place-photo'
      preLoaderRoute: typeof ApiPublicPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing-chat': {
      id: '/api/public/landing-chat'
      path: '/api/public/landing-chat'
      fullPath: '/api/public/landing-chat'
      preLoaderRoute: typeof ApiPublicLandingChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guide-chat-upload': {
      id: '/api/public/guide-chat-upload'
      path: '/api/public/guide-chat-upload'
      fullPath: '/api/public/guide-chat-upload'
      preLoaderRoute: typeof ApiPublicGuideChatUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guide-chat': {
      id: '/api/public/guide-chat'
      path: '/api/public/guide-chat'
      fullPath: '/api/public/guide-chat'
      preLoaderRoute: typeof ApiPublicGuideChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest-push': {
      id: '/api/public/guest-push'
      path: '/api/public/guest-push'
      fullPath: '/api/public/guest-push'
      preLoaderRoute: typeof ApiPublicGuestPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest-doc-upload': {
      id: '/api/public/guest-doc-upload'
      path: '/api/public/guest-doc-upload'
      fullPath: '/api/public/guest-doc-upload'
      preLoaderRoute: typeof ApiPublicGuestDocUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clicksign-webhook': {
      id: '/api/public/clicksign-webhook'
      path: '/api/public/clicksign-webhook'
      fullPath: '/api/public/clicksign-webhook'
      preLoaderRoute: typeof ApiPublicClicksignWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/taxonomia': {
      id: '/_authenticated/admin/taxonomia'
      path: '/taxonomia'
      fullPath: '/admin/taxonomia'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomiaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stakeholders': {
      id: '/_authenticated/admin/stakeholders'
      path: '/stakeholders'
      fullPath: '/admin/stakeholders'
      preLoaderRoute: typeof AuthenticatedAdminStakeholdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inteligencia': {
      id: '/_authenticated/admin/inteligencia'
      path: '/inteligencia'
      fullPath: '/admin/inteligencia'
      preLoaderRoute: typeof AuthenticatedAdminInteligenciaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ia': {
      id: '/_authenticated/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AuthenticatedAdminIaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hospedes': {
      id: '/_authenticated/admin/hospedes'
      path: '/hospedes'
      fullPath: '/admin/hospedes'
      preLoaderRoute: typeof AuthenticatedAdminHospedesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/guias': {
      id: '/_authenticated/admin/guias'
      path: '/guias'
      fullPath: '/admin/guias'
      preLoaderRoute: typeof AuthenticatedAdminGuiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/engajamento': {
      id: '/_authenticated/admin/engajamento'
      path: '/engajamento'
      fullPath: '/admin/engajamento'
      preLoaderRoute: typeof AuthenticatedAdminEngajamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/atendimento': {
      id: '/_authenticated/admin/atendimento'
      path: '/atendimento'
      fullPath: '/admin/atendimento'
      preLoaderRoute: typeof AuthenticatedAdminAtendimentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinatura': {
      id: '/_authenticated/admin/assinatura'
      path: '/assinatura'
      fullPath: '/admin/assinatura'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/administrativo': {
      id: '/_authenticated/admin/administrativo'
      path: '/administrativo'
      fullPath: '/admin/administrativo'
      preLoaderRoute: typeof AuthenticatedAdminAdministrativoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/recomendacoes-sigma/': {
      id: '/_authenticated/admin/recomendacoes-sigma/'
      path: '/recomendacoes-sigma'
      fullPath: '/admin/recomendacoes-sigma/'
      preLoaderRoute: typeof AuthenticatedAdminRecomendacoesSigmaIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cidades/': {
      id: '/_authenticated/admin/cidades/'
      path: '/cidades'
      fullPath: '/admin/cidades/'
      preLoaderRoute: typeof AuthenticatedAdminCidadesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/sinch-webhook': {
      id: '/api/public/whatsapp/sinch-webhook'
      path: '/api/public/whatsapp/sinch-webhook'
      fullPath: '/api/public/whatsapp/sinch-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappSinchWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-airbnb-ical': {
      id: '/api/public/cron/sync-airbnb-ical'
      path: '/api/public/cron/sync-airbnb-ical'
      fullPath: '/api/public/cron/sync-airbnb-ical'
      preLoaderRoute: typeof ApiPublicCronSyncAirbnbIcalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/saas-alerts': {
      id: '/api/public/cron/saas-alerts'
      path: '/api/public/cron/saas-alerts'
      fullPath: '/api/public/cron/saas-alerts'
      preLoaderRoute: typeof ApiPublicCronSaasAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-recommendations': {
      id: '/api/public/cron/refresh-recommendations'
      path: '/api/public/cron/refresh-recommendations'
      fullPath: '/api/public/cron/refresh-recommendations'
      preLoaderRoute: typeof ApiPublicCronRefreshRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-city-references': {
      id: '/api/public/cron/refresh-city-references'
      path: '/api/public/cron/refresh-city-references'
      fullPath: '/api/public/cron/refresh-city-references'
      preLoaderRoute: typeof ApiPublicCronRefreshCityReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-city-news': {
      id: '/api/public/cron/refresh-city-news'
      path: '/api/public/cron/refresh-city-news'
      fullPath: '/api/public/cron/refresh-city-news'
      preLoaderRoute: typeof ApiPublicCronRefreshCityNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/proactive-concierge': {
      id: '/api/public/cron/proactive-concierge'
      path: '/api/public/cron/proactive-concierge'
      fullPath: '/api/public/cron/proactive-concierge'
      preLoaderRoute: typeof ApiPublicCronProactiveConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/learning-loop': {
      id: '/api/public/cron/learning-loop'
      path: '/api/public/cron/learning-loop'
      fullPath: '/api/public/cron/learning-loop'
      preLoaderRoute: typeof ApiPublicCronLearningLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/recomendacoes-sigma/$cityKey': {
      id: '/_authenticated/admin/recomendacoes-sigma/$cityKey'
      path: '/recomendacoes-sigma/$cityKey'
      fullPath: '/admin/recomendacoes-sigma/$cityKey'
      preLoaderRoute: typeof AuthenticatedAdminRecomendacoesSigmaCityKeyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/$id': {
      id: '/_authenticated/admin/properties/$id'
      path: '/properties/$id'
      fullPath: '/admin/properties/$id'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cidades/$cityKey': {
      id: '/_authenticated/admin/cidades/$cityKey'
      path: '/cidades/$cityKey'
      fullPath: '/admin/cidades/$cityKey'
      preLoaderRoute: typeof AuthenticatedAdminCidadesCityKeyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/$id_/conversas': {
      id: '/_authenticated/admin/properties/$id_/conversas'
      path: '/properties/$id/conversas'
      fullPath: '/admin/properties/$id/conversas'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdConversasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/$id_/acessos': {
      id: '/_authenticated/admin/properties/$id_/acessos'
      path: '/properties/$id/acessos'
      fullPath: '/admin/properties/$id/acessos'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdAcessosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdministrativoRoute: typeof AuthenticatedAdminAdministrativoRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAssinaturaRoute: typeof AuthenticatedAdminAssinaturaRoute
  AuthenticatedAdminAtendimentoRoute: typeof AuthenticatedAdminAtendimentoRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEngajamentoRoute: typeof AuthenticatedAdminEngajamentoRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminGuiasRoute: typeof AuthenticatedAdminGuiasRoute
  AuthenticatedAdminHospedesRoute: typeof AuthenticatedAdminHospedesRoute
  AuthenticatedAdminIaRoute: typeof AuthenticatedAdminIaRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminInteligenciaRoute: typeof AuthenticatedAdminInteligenciaRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminStakeholdersRoute: typeof AuthenticatedAdminStakeholdersRoute
  AuthenticatedAdminTaxonomiaRoute: typeof AuthenticatedAdminTaxonomiaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCidadesCityKeyRoute: typeof AuthenticatedAdminCidadesCityKeyRoute
  AuthenticatedAdminPropertiesIdRoute: typeof AuthenticatedAdminPropertiesIdRoute
  AuthenticatedAdminRecomendacoesSigmaCityKeyRoute: typeof AuthenticatedAdminRecomendacoesSigmaCityKeyRoute
  AuthenticatedAdminCidadesIndexRoute: typeof AuthenticatedAdminCidadesIndexRoute
  AuthenticatedAdminRecomendacoesSigmaIndexRoute: typeof AuthenticatedAdminRecomendacoesSigmaIndexRoute
  AuthenticatedAdminPropertiesIdAcessosRoute: typeof AuthenticatedAdminPropertiesIdAcessosRoute
  AuthenticatedAdminPropertiesIdConversasRoute: typeof AuthenticatedAdminPropertiesIdConversasRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdministrativoRoute: AuthenticatedAdminAdministrativoRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAssinaturaRoute: AuthenticatedAdminAssinaturaRoute,
  AuthenticatedAdminAtendimentoRoute: AuthenticatedAdminAtendimentoRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEngajamentoRoute: AuthenticatedAdminEngajamentoRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminGuiasRoute: AuthenticatedAdminGuiasRoute,
  AuthenticatedAdminHospedesRoute: AuthenticatedAdminHospedesRoute,
  AuthenticatedAdminIaRoute: AuthenticatedAdminIaRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedAdminInteligenciaRoute: AuthenticatedAdminInteligenciaRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminStakeholdersRoute: AuthenticatedAdminStakeholdersRoute,
  AuthenticatedAdminTaxonomiaRoute: AuthenticatedAdminTaxonomiaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCidadesCityKeyRoute: AuthenticatedAdminCidadesCityKeyRoute,
  AuthenticatedAdminPropertiesIdRoute: AuthenticatedAdminPropertiesIdRoute,
  AuthenticatedAdminRecomendacoesSigmaCityKeyRoute:
    AuthenticatedAdminRecomendacoesSigmaCityKeyRoute,
  AuthenticatedAdminCidadesIndexRoute: AuthenticatedAdminCidadesIndexRoute,
  AuthenticatedAdminRecomendacoesSigmaIndexRoute:
    AuthenticatedAdminRecomendacoesSigmaIndexRoute,
  AuthenticatedAdminPropertiesIdAcessosRoute:
    AuthenticatedAdminPropertiesIdAcessosRoute,
  AuthenticatedAdminPropertiesIdConversasRoute:
    AuthenticatedAdminPropertiesIdConversasRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GSlugRouteChildren {
  GSlugExplorarRoute: typeof GSlugExplorarRoute
  GSlugIndexRoute: typeof GSlugIndexRoute
}

const GSlugRouteChildren: GSlugRouteChildren = {
  GSlugExplorarRoute: GSlugExplorarRoute,
  GSlugIndexRoute: GSlugIndexRoute,
}

const GSlugRouteWithChildren = GSlugRoute._addFileChildren(GSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiancaRoute: ConfiancaRoute,
  McpRoute: McpRoute,
  PainelRoute: PainelRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  GSlugRoute: GSlugRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicClicksignWebhookRoute: ApiPublicClicksignWebhookRoute,
  ApiPublicGuestDocUploadRoute: ApiPublicGuestDocUploadRoute,
  ApiPublicGuestPushRoute: ApiPublicGuestPushRoute,
  ApiPublicGuideChatRoute: ApiPublicGuideChatRoute,
  ApiPublicGuideChatUploadRoute: ApiPublicGuideChatUploadRoute,
  ApiPublicLandingChatRoute: ApiPublicLandingChatRoute,
  ApiPublicPlacePhotoRoute: ApiPublicPlacePhotoRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicCronLearningLoopRoute: ApiPublicCronLearningLoopRoute,
  ApiPublicCronProactiveConciergeRoute: ApiPublicCronProactiveConciergeRoute,
  ApiPublicCronRefreshCityNewsRoute: ApiPublicCronRefreshCityNewsRoute,
  ApiPublicCronRefreshCityReferencesRoute:
    ApiPublicCronRefreshCityReferencesRoute,
  ApiPublicCronRefreshRecommendationsRoute:
    ApiPublicCronRefreshRecommendationsRoute,
  ApiPublicCronSaasAlertsRoute: ApiPublicCronSaasAlertsRoute,
  ApiPublicCronSyncAirbnbIcalRoute: ApiPublicCronSyncAirbnbIcalRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWhatsappSinchWebhookRoute: ApiPublicWhatsappSinchWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
